name: "Checkout with optional submodules"
description: "Checkout a repository and optionally its submodules using a provided SSH key."
inputs:
  ssh-private-key:
    description: "SSH private key for accessing the repository."
    required: true
  ssh-public-key:
    description: "SSH public key for accessing the repository."
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository with token
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ssh-key: ${{ inputs.ssh-private-key }}
        persist-credentials: false

    - name: Checkout submodules
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh-private-key }}" > ~/.ssh/id_rsa
        echo "${{ inputs.ssh-public-key }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/id_rsa.pub
        git submodule update --init --recursive
      shell: bash 
